Repository tanay105/Classroom-Bot, pull requests merged in 2020-10, with the labels that each got.

#16 ISSUE 15: adding debug dockefile for UI service
  Makefile
  ui/debug.dockerfile
Labels: enhancement

#18 adding docker compose build for parallel processing
  Makefile
Labels: enhancement, good first issue

#20 Issues 19: Adding support for codecoverage report generation
  backend-service/bot_server/bot_server/settings.py
  backend-service/bot_server/requirements.txt
  backend-service/test.Dockerfile
  backend-service/test_script.sh
Labels: enhancement

#26 Issue 24 Adding schedule management APIs from proxy service
  backend-service/bot_proxy_server/proxy_service/dispatchers/command_dispatcher.py
  backend-service/bot_proxy_server/proxy_service/handlers/command_handlers.py
Labels: enhancement

#28 ISSUE 27: adding more file types to git ignore file
  .gitignore
Labels: bug

#30 ISSUE 29: adding bot server calls for schedule management API
  backend-service/bot_proxy_server/proxy_service/bot_server_http_calls/schedule.py
  backend-service/bot_proxy_server/proxy_service/handlers/command_handlers.py
Labels: bug

#33 ISSUE 32: Adding code cov badge to README
  README.md
Labels: documentation

#45 Issue 34 adding bot_server APIs for schedule management
  backend-service/bot_proxy_server/proxy_service/bot_server_http_calls/schedule.py
  backend-service/bot_proxy_server/proxy_service/dispatchers/command_dispatcher.py
  backend-service/bot_proxy_server/proxy_service/handlers/command_handlers.py
  backend-service/bot_proxy_server/proxy_service/views.py
  backend-service/bot_server/api/migrations/0009_schedule.py
  backend-service/bot_server/api/models.py
  backend-service/bot_server/api/request_dispatcher.py
  backend-service/bot_server/api/request_handler.py
  backend-service/bot_server/api/serializer.py
  backend-service/bot_server/api/urls.py
  backend-service/bot_server/api/views.py
Labels: enhancement

#54 Issue 48 Updating documentation for schedule commands
  backend-service/bot_proxy_server/docs/addbottoyourworkspace.md
  backend-service/bot_proxy_server/docs/setup.md
Labels: documentation

#50 User test plan and survey
  docs/test_plan/end_user_test_plan.md
  docs/test_plan/performance_test_plan.md
  docs/test_plan/survey/moderated_user_testing_survey.md
  docs/test_plan/survey/user_testing_survey.md
Labels: test_plan

#58 adding license and youtube views badge in README
  README.md
Labels: bug

#66 Update README.md
  README.md
Labels: documentation
